In [1]:
# Importation des packaques
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re

In [2]:
# Importation du fichier de scraping
df = pd.read_csv('vgsales_scraping.csv')
#print(df.isnull().sum())

# Scraping Metascore
# On recherche les nombres dans Metascore correspond respectivement à la note et au nombre de vote
r = re.compile(r"[0-9]+")

# On crée les 2 conteneurs qui vont recueillir ces infos
metascorewrap_note = []
metascorewrap_nbvote = []
count = 0

for i in df['metascorewrap']:
    metascorewrap = r.findall(i)
    if len(metascorewrap)>1 :
        #print(count," : ",metascorewrap)
        #print(type(metascorewrap_note))
        metascorewrap_note.append(metascorewrap[0])
        metascorewrap_nbvote.append(metascorewrap[1])
    else :
        metascorewrap_note.append(np.nan)
        metascorewrap_nbvote.append(np.nan)
    count+=1
    
# On recherche les floats dans Userscore correspond respectivement à la note et au nombre de vote
r = re.compile(r"[0-9]+\.?[0-9]+")

# On crée les 2 conteneurs qui vont recueillir ces infos
userscorewrap_note = []
userscorewrap_nbvote = []
count = 0
df['metaNote']=metascorewrap_note
df['metaNbVote']=metascorewrap_nbvote

for i in df['userscorewrap']:
    userscorewrap = r.findall(i)
    if len(userscorewrap)>1 :
        #print(count," : ",userscorewrap)
        #print(type(metascorewrap_note))
        userscorewrap_note.append(userscorewrap[0])
        userscorewrap_nbvote.append(userscorewrap[1])
    else :
        userscorewrap_note.append(np.nan)
        userscorewrap_nbvote.append(np.nan)
    count+=1
df['userNote']=userscorewrap_note
df['userNbVote']=userscorewrap_nbvote
    
# Comparatif entre le nom du dataset et le nom sur Metacritic
samename = []
for i,j in zip(df['Name'],df['gamename']):
    if (i in j) or (j in i) : # Je fais le test dans les 2 sens, voir index 16595
        samename.append(1)
    else :
        samename.append(0)
df['samename']=samename

In [3]:
#print(df['metascorewrap'][52])
#print(df['userscorewrap'][0])

df=df.drop(['metascorewrap','developper','userscorewrap','nbvotes','description','top','nbratings','metascore','ratings'],axis=1)
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,metaNote,metaNbVote,userNote,userNbVote,samename
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,76,51,8.1,453,1
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,84,14,8.5,98,1
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,82,73,8.4,1047,1
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,80,73,8.2,293,1
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,67,17,8.3,159,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,0
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,50,19,NaN,NaN,1
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,29,4,NaN,NaN,1
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,0
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,50,10,NaN,NaN,1

In [4]:
# Calcul du nombre de bons jeux (même nom) trouvés
print(df['samename'].value_counts())
print("length :",len(df))

# Suppression des mauvais jeux (pas le même nom)
df.drop(df.loc[df['samename']==0].index, inplace=True)
df

1    11540
0     5058
Name: samename, dtype: int64
length : 16598

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,metaNote,metaNbVote,userNote,userNbVote,samename
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,76,51,8.1,453,1
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,84,14,8.5,98,1
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,82,73,8.4,1047,1
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,80,73,8.2,293,1
5,6,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,83,27,8.2,258,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16591,16594,Myst IV: Revelation,PC,2004.0,Adventure,Ubisoft,0.01,0.00,0.00,0.00,0.01,82,36,NaN,NaN,1
16592,16595,Plushees,DS,2008.0,Simulation,Destineer,0.01,0.00,0.00,0.00,0.01,1,3,NaN,NaN,1
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,50,19,NaN,NaN,1
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,29,4,NaN,NaN,1
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,50,10,NaN,NaN,1

In [ ]:
df.to_csv("vgsales.csv", index = False)